
examples = [
    """Question: When did Amelia attend Breakfast Meeting on 2022/01/16?\n\nThought: The keyword "Amelia Breakfast Meeting 2022/01/16" seems to be relevant for the RetrieveAgenda tool, which can search for agenda items related to a specific keyword.\n\nAction: RetrieveAgenda\n\nAction Input: {"keyword": "Amelia Breakfast Meeting 2022/01/16"}\n\nObservation: Amelia has a lunch event with her colleagues on September 17, 2022. The event will start at 12:00 PM and will last an hour until 1:00 PM. The location for their lunch is at Toast Restaurant.\nOn May 2nd, 2022, Amelia will be attending a Business Luncheon at The Grand Hyatt Hotel. The event will start at 12:30 PM and end at 2:00 PM.\nOn Sunday, January 16th 2022, Amelia has a breakfast meeting scheduled at The Golden Spoon Café. The event is set to start promptly at 7:30 AM and will continue until 9:00 AM. This early morning meeting is likely an important business gathering, and Amelia will need to arrive on time to make the most of it. The Golden Spoon Café is a charming spot, perfect for a morning coffee and a hearty breakfast, which should provide a comfortable and welcoming setting for the meeting. Overall, this breakfast meeting seems like a great opportunity for Amelia to network, collaborate, and kick-start her day with some delicious food and stimulating conversation.\n\nThought: According to the information, Amelia attended the Breakfast Meeting at 7:30 AM on 2022/01/16 at The Golden Spoon Café.\n\nAction: Finish\n\nAction Input: {"answer": "7:30 AM"}\n\nObservation: Answer is CORRECT.""",

    """Question: How long did Joshua attend Gym Workout on 2022/06/03?\n\nThought: To determine the duration of Joshua's gym workout on 2022/06/03, I need to look for records or an agenda related to Joshua's gym activities on that specific date.\n\nAction: RetrieveAgenda\n\nAction Input: {"keyword": "Joshua Gym Workout 2022/06/03"}\n\nObservation: On May 11, 2022, Joshua has scheduled a Fitness class that will take place at Gold's Gym. The class is set to commence from 9:00 AM and will run until 10:00 AM. This is an exciting opportunity for Joshua to work on his physical fitness and improve his overall wellbeing. The location is an excellent choice for this kind of activity with modern facilities that are specifically designed to meet all fitness goals and requirements. With this fitness class, Joshua is set to achieve his fitness goals, stay healthy, and enhance his quality of life.\nOn June 3rd, 2022 (Friday), Joshua is scheduled to hit the gym for a solid workout session. He plans to start his session early, at exactly 6:00 in the morning, at the Equinox Fitness Club. This two-hour fitness activity will end at exactly 8:00 AM. Joshua is determined to squeeze in this healthy routine to keep himself in shape and promote overall wellbeing.\nRichard has a gym workout session scheduled for March 27, 2022, at Fitness Paradise Center. The session is set to start at 11:00 AM and end at 12:00 PM. During this hour-long session, Richard will engage in various physical exercises designed to help him maintain his physical fitness and improve his health. Fitness Paradise Center provides an ideal environment for him to achieve his fitness goals. During this session, Richard will work out using various machines and weights, with the guidance of a professional trainer. The gym workout session promises to be both challenging and rewarding for Richard, as he strives to maintain a healthy lifestyle.\n\nThought: The observation from the RetrieveAgenda tool indicates that Joshua's gym workout on 2022/06/03 was at Equinox Fitness Club and was planned to be a two-hour session from 9:00 AM to 10:00 AM.\n\nAction: Finish\n\nAction Input: {"answer": "2:00:00"}\n\nObservation: Answer is CORRECT.""",

    """Question: Where did Batting cage practice that Isabella attended take place on 2022/12/25?\n\nThought: To find out the location of the batting cage practice Isabella attended on 2022/12/25, I should use the RetrieveAgenda tool. The keyword should include Isabella, the activity, and the date specified.\n\nAction: RetrieveAgenda\n\nAction Input: {"keyword": "Batting cage practice Isabella 2022/12/25"}\n\nObservation: Isabella has batting cage practice scheduled on Christmas Day, December 25th, 2022. The practice starts at 2:00 PM and runs until 4:00 PM at The Batcade Studios. She'll be working on her batting skills, perhaps gearing up for a tournament or game in the near future. It might not seem like the most traditional way to spend the holiday, but for Isabella, it's a chance to stay focused on her goals and keep improving.\nGrace has an event at The Batcade on November 4th, 2022. The event is all about batting cages, and it's scheduled to start at 11:00 AM and end at 2:00 PM.\nOn December 28th, 2022, Hannah has an exciting event scheduled at the Chelsea Piers Sports & Entertainment Complex. She will be headed to the Batting Cages for a couple of hours of fun-filled activities. The event will kick off at 10:00 AM sharp and will run until 12:00 PM. Hannah will be practicing her swings, hits, and aiming skills inside the batting cages, surrounded by state-of-the-art sports equipment and a supportive environment. The location is perfect for this activity, as the Chelsea Piers Sports & Entertainment Complex has some of the best-in-class indoor sports facilities in the city. It's a great way for Hannah to spend her day, honing her skills, and enjoying some fantastic sports action.\n\nThought: The batting cage practice that Isabella attended on 2022/12/25 took place at The Batcade Studios.\n\nAction: Finish\n\nAction Input: {"answer": "The Batcade Studios"}\n\nObservation: Answer is CORRECT.""",

]



# ## When did Amelia attend Breakfast Meeting on 2022/01/16?
# # 7:30 AM




# ## Who attended Meetup activity between 7:00 PM and 9:00 PM on 2022/05/26 in Local Pub, Legion Brewing?
# # Madison
# """Question: Who attended Meetup activity between 7:00 PM and 9:00 PM on 2022/05/26 in Local Pub, Legion Brewing?\n\nThought: To find out who attended the Meetup activity between 7:00 PM and 9:00 PM on 2022/05/26 in Local Pub, Legion Brewing, I need to use the RetrieveAgenda tool with a keyword that includes the date, time, and location specified.\n\nAction: Use the RetrieveAgenda tool to search for the agenda.\n\nAction Input: {"keyword": "Meetup 2022/05/26 7:00 PM 9:00 PM Local Pub Legion Brewing"}\n\nObservation: On May 26th 2022, a Meetup activity will take place in Madison at the Local Pub, Legion Brewing. The event will start at 7:00 PM and will run until 9:00 PM. Attendees will gather together for a fun and social evening, getting to know one another and bonding over their shared interests. The casual and relaxed vibe of the pub will provide the perfect backdrop for this event, fostering a comfortable and welcoming atmosphere where everyone can feel at ease. Whether it's your first time attending a Meetup, or you're a seasoned pro, this promises to be a great night and an opportunity to make some new connections.\nAidan is hosting a Meetup group at The Liberty Bar on December 13th, 2022. The event starts at 7:00 PM and ends at 9:00 PM. It's a great opportunity for people to connect and network with others who share similar interests. Don't miss out on this chance to expand your social circle and meet new people in a fun and relaxed environment!\nOn June 25th, 2022, join Andrew and other beer enthusiasts for a beer tasting event at a Craft Brewery. The event will start at 6:00 PM and end at 9:00 PM, providing you with a three-hour window to indulge in some of the most exquisite beer varieties and learn more about their flavors and brewing process. The venue, a Craft Brewery, is the perfect setting for this event and is sure to provide a cozy and inviting atmosphere. So come, sample some of the finest beer options on the market, enjoy the company of like-minded beer enthusiasts, and make the most of this exciting evening of beer tasting and discovery!\n\nThought: According to the information, Madison attended Meetup activity between 7:00 PM and 9:00 PM on 2022/05/26 in Local Pub, Legion Brewing.\n\nAction: Finish\n\nAction Input: {"answer": "Madison"}\n\nObservation: Answer is CORRECT."""


# ## How long did Joshua attend Gym Workout on 2022/06/03?
# # 2:00:00

# """Question: How long did Joshua attend Gym Workout on 2022/06/03?\n\nThought: To determine the duration of Joshua's gym workout on 2022/06/03, I need to look for records or an agenda related to Joshua's gym activities on that specific date.\n\nAction: RetrieveAgenda\n\nAction Input: {"keyword": "Joshua Gym Workout 2022/06/03"}\n\nObservation: On May 11, 2022, Joshua has scheduled a Fitness class that will take place at Gold's Gym. The class is set to commence from 9:00 AM and will run until 10:00 AM. This is an exciting opportunity for Joshua to work on his physical fitness and improve his overall wellbeing. The location is an excellent choice for this kind of activity with modern facilities that are specifically designed to meet all fitness goals and requirements. With this fitness class, Joshua is set to achieve his fitness goals, stay healthy, and enhance his quality of life.\nOn June 3rd, 2022 (Friday), Joshua is scheduled to hit the gym for a solid workout session. He plans to start his session early, at exactly 6:00 in the morning, at the Equinox Fitness Club. This two-hour fitness activity will end at exactly 8:00 AM. Joshua is determined to squeeze in this healthy routine to keep himself in shape and promote overall wellbeing.\nRichard has a gym workout session scheduled for March 27, 2022, at Fitness Paradise Center. The session is set to start at 11:00 AM and end at 12:00 PM. During this hour-long session, Richard will engage in various physical exercises designed to help him maintain his physical fitness and improve his health. Fitness Paradise Center provides an ideal environment for him to achieve his fitness goals. During this session, Richard will work out using various machines and weights, with the guidance of a professional trainer. The gym workout session promises to be both challenging and rewarding for Richard, as he strives to maintain a healthy lifestyle.\n\nThought: The observation from the RetrieveAgenda tool indicates that Joshua's gym workout on 2022/06/03 was at Equinox Fitness Club and was planned to be a two-hour session from 9:00 AM to 10:00 AM.\n\nAction: Finish\n\nAction Input: {"answer": "2:00:00"}\n\nObservation: Answer is CORRECT."""


# ## Where did Batting cage practice that Isabella attended take place on 2022/12/25?
# # The Batcade Studios
# """Question: Where did Batting cage practice that Isabella attended take place on 2022/12/25?\n\nThought: To find out the location of the batting cage practice Isabella attended on 2022/12/25, I should use the RetrieveAgenda tool. The keyword should include Isabella, the activity, and the date specified.\n\nAction: RetrieveAgenda\n\nAction Input: {"keyword": "Batting cage practice Isabella 2022/12/25"}\n\nObservation: Isabella has batting cage practice scheduled on Christmas Day, December 25th, 2022. The practice starts at 2:00 PM and runs until 4:00 PM at The Batcade Studios. She'll be working on her batting skills, perhaps gearing up for a tournament or game in the near future. It might not seem like the most traditional way to spend the holiday, but for Isabella, it's a chance to stay focused on her goals and keep improving.\nGrace has an event at The Batcade on November 4th, 2022. The event is all about batting cages, and it's scheduled to start at 11:00 AM and end at 2:00 PM.\nOn December 28th, 2022, Hannah has an exciting event scheduled at the Chelsea Piers Sports & Entertainment Complex. She will be headed to the Batting Cages for a couple of hours of fun-filled activities. The event will kick off at 10:00 AM sharp and will run until 12:00 PM. Hannah will be practicing her swings, hits, and aiming skills inside the batting cages, surrounded by state-of-the-art sports equipment and a supportive environment. The location is perfect for this activity, as the Chelsea Piers Sports & Entertainment Complex has some of the best-in-class indoor sports facilities in the city. It's a great way for Hannah to spend her day, honing her skills, and enjoying some fantastic sports action.\n\nThought: The batting cage practice that Isabella attended on 2022/12/25 took place at The Batcade Studios.\n\nAction: Finish\n\nAction Input: {"answer": "The Batcade Studios"}\n\nObservation: Answer is CORRECT."""
